services:

  fs:
    build: ./
    command: dotnet run --project src/Server/Server.fsproj
    volumes:
      - .:/app
    ports:
      - 8085:8085

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
